In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,11],[12,13]])
a+b

array([[11, 13],
       [15, 17]])

In [3]:
a.dot(b) #array multiplication is different from matrix multiplication

array([[34, 37],
       [78, 85]])

In [4]:
np.transpose(a)

array([[1, 3],
       [2, 4]])