In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [2]:
a+2

array([[3, 4],
       [5, 6]])

In [4]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [5]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [6]:
a+b

array([11, 22, 33, 44])

In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,1],[2,1,1]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b

array([[1, 2, 1],
       [2, 1, 1]])

In [9]:
a+b

array([[2, 4, 4],
       [6, 6, 7]])

In [10]:
np.subtract(a,b)

array([[0, 0, 2],
       [2, 4, 5]])