In [1]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a.shape

(10,)

In [3]:
b=np.reshape(a,(5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
b.shape

(5, 2)

In [5]:
a=np.arange(10)
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
np.resize(a,(2,3))
#resize will change total no of elements reshape won't

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
b

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
b.flatten()
#it will return copy
#method

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.ravel(b) 
 #function at library level
 #it will return copy only if needed or it will just return the view

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [13]:
b=np.transpose(a)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [17]:
np.shape(b)

(2, 2, 3)

In [18]:
np.swapaxes(a,0,1) #it interchange the axis of the array

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [2]:
import numpy as np
a=np.arange(1,5)
b=np.arange(6)
np.concatenate((a,b))


array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [5]:
a=np.arange(5)
b=np.arange(5)
np.vstack((a,b)) #the concatinating axis should be equal
#except 1d array vstack behave same as concatenate

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [6]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [9]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [3]:
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.insert(a,1,50)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.insert(a,(1,3),50)

array([ 1, 50,  2,  3, 50,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
np.insert(a,1,23)#if you don't specify axis it will flatten the array

array([ 1, 23,  2,  3,  4])

In [9]:
np.insert(a,1,23,axis=0)

array([[ 1,  2],
       [23, 23],
       [ 3,  4]])